### ISSUE TITLE
Profile creation: profile undefined

### ISSUE THREAD

**Issue by Nehaxfr** [Make-Tarkov-Great-Again/MTGA-Backend#21]
Under mysterious circunstances, when creating a new profile, it fail at nickname validation:

`err: {
      "type": "TypeError",
      "message": "Cannot convert undefined or null to object",
      "stack":
          TypeError: Cannot convert undefined or null to object
              at Function.entries (<anonymous>)
              at Function.ifAvailableNickname (D:\repos\Tarkov\MakeTarkovGreatAgain\MTGA-Backend\plugins\models\Profile.js:37:45)
              at Function.clientGameProfileNicknameValidate (D:\repos\Tarkov\MakeTarkovGreatAgain\MTGA-Backend\plugins\controllers\client\GameController.js:148:40)
              at Object.<anonymous> (D:\repos\Tarkov\MakeTarkovGreatAgain\MTGA-Backend\plugins\routes\client.js:49:30)
              at preHandlerCallback (D:\repos\Tarkov\MakeTarkovGreatAgain\MTGA-Backend\node_modules\fastify\lib\handleRequest.js:126:28)
              at preValidationCallback (D:\repos\Tarkov\MakeTarkovGreatAgain\MTGA-Backend\node_modules\fastify\lib\handleRequest.js:110:5)
              at handler (D:\repos\Tarkov\MakeTarkovGreatAgain\MTGA-Backend\node_modules\fastify\lib\handleRequest.js:74:7)
              at D:\repos\Tarkov\MakeTarkovGreatAgain\MTGA-Backend\node_modules\fastify\lib\contentTypeParser.js:169:9
              at AsyncResource.runInAsyncScope (node:async_hooks:202:9)
              at done (D:\repos\Tarkov\MakeTarkovGreatAgain\MTGA-Backend\node_modules\fastify\lib\contentTypeParser.js:163:14)
    }`

The profile collection retrieved in the database is undefined.

![Image](https://user-images.githubusercontent.com/74174676/178450201-21fa4a29-2f3d-4111-a87d-5463f66b4500.png)

The server was closed, I deleted all my accounts, started server and registered a new account.

**Comment by Nehaxfr** [comment]
King fixed it
